imports:
    - { resource: config.yml }

framework:
    templating:
        assets_base_urls:
            http: ["http://assets1.deudtens.com", "http://assets2.deudtens.com"] }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
parameters:
    cdn_local_path: "/var/www/cdn/spacepicturesjam"
