parameters:
    database_driver: pdo_mysql
    database_host: "%spj.database.host%"
    database_port: null
    database_name: "%spj.database.name%"
    database_user: "%spj.database.user%"
    database_password: "%spj.database.password%"
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: dsfkjdfdhsk6776Dd-dDlo9
