parameters:
    database_driver: pdo_mysql
    database_host: SYMFONY__SPJ__DATABASE__HOST
    database_port: null
    database_name:     SYMFONY__SPJ__DATABASE__NAME
    database_user:     SYMFONY__SPJ__DATABASE__USER
    database_password: SYMFONY__SPJ__DATABASE__PASSWORD
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: dsfkjdfdhsk6776Dd-dDlo9
