security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        secured_area:
            pattern:    ^/admin/
            form_login:
                check_path: _security_check
                login_path: /login
            logout:
                path:   _demo_logout
                target: _demo

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
