login:
    defaults:  { _controller: SPJGameBundle:User:login }
    pattern: /login

login_check:
    pattern:   /login_check

signup:
    defaults:  { _controller: SPJGameBundle:User:signup }
    pattern: /inscription

signup_check:
    pattern: /signup_check
    defaults: { _controller: SPJGameBundle:User:signupCheck }

challenge_list:
    pattern: /
    defaults: { _controller: SPJGameBundle:Challenge:list }

login:
    pattern: /login
    defaults: { _controller: SPJGameBundle:User:login }

SPJGameBundle_admin_challenge:
        resource: "@SPJGameBundle/Resources/config/routing/challenge.yml"
        prefix:   /admin/challenge
