login:
    defaults:  { _controller: SPJGameBundle:User:login }
    pattern: /login

login_check:
    pattern:   /login_check

facebook_login_check:
    pattern:   /facebook/login_check
    defaults: { _controller: SPJGameBundle:User:facebookLoginCheck }

logout:
    pattern:   /logout

signup:
    pattern: /inscription
    defaults: { _controller: SPJGameBundle:User:signup }

signup_check:
    pattern: /signup_check
    defaults: { _controller: SPJGameBundle:User:signupCheck }

challenge_list:
    pattern: /
    defaults: { _controller: SPJGameBundle:Challenge:list }

login:
    pattern: /login
    defaults: { _controller: SPJGameBundle:User:login }

picture_create:
    pattern:  /challenge/{challengeId}/picture/create
    defaults: { _controller: SPJGameBundle:Picture:create }

challenge_picture_list:
    pattern:  /challenge/{challengeId}/pictures
    defaults: { _controller: SPJGameBundle:Picture:challengeList }

challenge_user_picture_show:
    pattern:  /challenge/{challengeId}/user/picture
    defaults: { _controller: SPJGameBundle:Picture:challengeUserShow }

SPJGameBundle_admin_challenge:
        resource: "@SPJGameBundle/Resources/config/routing/challenge.yml"
        prefix:   /admin/challenge
