login:
    defaults:  { _controller: SPJGameBundle:User:login }
    pattern: /login

login_check:
    pattern:   /login_check

challenge_list:
    pattern: /
    defaults: { _controller: SPJGameBundle:Challenge:list }

SPJGameBundle_admin_challenge:
        resource: "@SPJGameBundle/Resources/config/routing/challenge.yml"
        prefix:   /admin/challenge

login:
    pattern: /login
    defaults: { _controller: SPJGameBundle:User:login }
