list:
    pattern: /
    defaults: { _controller: SPJGameBundle:Challenge:list }

SPJGameBundle_admin_challenge:
        resource: "@SPJGameBundle/Resources/config/routing/challenge.yml"
        prefix:   /admin/challenge
