services:
    challenge_repository:
        class: SPJ\GameBundle\Repository\ChallengeRepository
        arguments: [SPJGameBundle:Challenge]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository

    picture_upload:
        class: SPJ\GameBundle\Service\PictureUploadService
        arguments: [%cdn_local_path%]
