parameters:
#    spj_game.example.class: SPJ\GameBundle\Example

services:
#    spj_game.example:
#        class: %spj_game.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
