services:
    challenge_repository:
        class: SPJ\GameBundle\Repository\ChallengeRepository
        arguments: [SPJGameBundle:Challenge]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository

    picture_upload:
        class: SPJ\GameBundle\Service\PictureUploadService
        arguments: [@image_filter, %kernel.root_dir%, %cdn_local_path%, %secret%]

    image_filter:
        class: SPJ\GameBundle\Service\ImageFilterService
