services:
    challenge_repository:
        class: SPJ\GameBundle\Repository\ChallengeRepository
        arguments: [SPJGameBundle:Challenge]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
