services:
    picture_repository:
        class: SPJ\GameBundle\Repository\PictureRepository
        arguments: [SPJGameBundle:Picture]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository

    challenge_repository:
        class: SPJ\GameBundle\Repository\ChallengeRepository
        arguments: [SPJGameBundle:Challenge]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository

    user_repository:
        class: SPJ\GameBundle\Repository\UserRepository
        arguments: [SPJGameBundle:User]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository

    picture_upload:
        class: SPJ\GameBundle\Service\PictureUploadService
        arguments: [@image_filter, %kernel.root_dir%, %cdn_local_path%, %secret%]

    image_filter:
        class: SPJ\GameBundle\Service\ImageFilterService

    facebook:
        class: SPJ\GameBundle\Service\FacebookService
        arguments: [%facebook_app_id%, %facebook_app_secret%, @router, @user_repository, @security.context, @security.encoder_factory, @doctrine.orm.entity_manager]
